// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCz3Xe-wksbUoub3CegwNfuAdaSJwJWuSo',
    appId: '1:342593624444:web:f0a65c9b65fe45d4b32cf9',
    messagingSenderId: '342593624444',
    projectId: 'reminote-f5a59',
    authDomain: 'reminote-f5a59.firebaseapp.com',
    databaseURL: 'https://reminote-f5a59-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'reminote-f5a59.firebasestorage.app',
    measurementId: 'G-XVWV2CQV3J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6LMzdEidmTbxodeBpX3N7PK4WyM6naBo',
    appId: '1:342593624444:android:bbef8bc72b4e523cb32cf9',
    messagingSenderId: '342593624444',
    projectId: 'reminote-f5a59',
    databaseURL: 'https://reminote-f5a59-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'reminote-f5a59.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7o0xr-cVzq3hGAWXMomKyEm15BDd0ktI',
    appId: '1:342593624444:ios:f12d4bb637a4dca7b32cf9',
    messagingSenderId: '342593624444',
    projectId: 'reminote-f5a59',
    databaseURL: 'https://reminote-f5a59-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'reminote-f5a59.firebasestorage.app',
    iosBundleId: 'com.example.studyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7o0xr-cVzq3hGAWXMomKyEm15BDd0ktI',
    appId: '1:342593624444:ios:f12d4bb637a4dca7b32cf9',
    messagingSenderId: '342593624444',
    projectId: 'reminote-f5a59',
    databaseURL: 'https://reminote-f5a59-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'reminote-f5a59.firebasestorage.app',
    iosBundleId: 'com.example.studyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCz3Xe-wksbUoub3CegwNfuAdaSJwJWuSo',
    appId: '1:342593624444:web:5ea61b81eb4936c9b32cf9',
    messagingSenderId: '342593624444',
    projectId: 'reminote-f5a59',
    authDomain: 'reminote-f5a59.firebaseapp.com',
    databaseURL: 'https://reminote-f5a59-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'reminote-f5a59.firebasestorage.app',
    measurementId: 'G-J8PEC60250',
  );
}
